version: '3.8'

services:
  frontend:
    build: .
    container_name: epidemic-frontend
    volumes:
      # Monte tout le répertoire du projet
      - .:/app
      # Ignore node_modules pour éviter les conflits OS
      - /app/node_modules
      # Cache npm persistant
      - npm-cache:/root/.npm
      # Pour Vite HMR
      - /app/.vite
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # URL de votre API backend
      - VITE_API_URL=http://epidemic-api:5000
      # Configuration Vite
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    ports:
      # Port principal de Vite (par défaut)
      - "5173:5173"
      # Port alternatif si configuré
      - "3000:3000"
    networks:
      - epidemic-network
    tty: true
    stdin_open: true
    # Pour le développement, on garde le container actif
    command: tail -f /dev/null
    # Redémarre automatiquement si crash
    restart: unless-stopped

networks:
  epidemic-network:
    driver: bridge
    # Permet la communication avec d'autres containers docker
    external: true

volumes:
  npm-cache: